title: darryl.sh
email: rootbeersoup@gmail.com
description: 
url: https://darryl.sh
timezone: America/Chicago

includes_dir: includes
layouts_dir: layouts
sass:
  sass_dir: assets
  style: compressed

permalink: /:title/

plugins:
  - jekyll-octicons

github_username:  rootbeersoup
google_analytics: UA-117240781-1
markdown: redcarpet
include: ["_posts", "assets", "img"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]

