baseURL = "https://darryl.cx"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "Darryl Abbate"

watch = true
newContentEditor = "vim"

pygmentsUseClasses = true
pygmentsCodeFences = true

[frontmatter]
  date = [":filename", ":default"]
